### ISSUE TITLE
How to get length value in the dataset

### ISSUE THREAD

**Issue by Geaming-CHN** [THUDM/LongAlign#7]
How to get the length value in the dataset, I tried to calculate the string length of the data or the number of words by `split()` but it doesn't match the length value.

![image](https://github.com/THUDM/LongAlign/assets/71267655/391e25f1-6e9f-49f1-9009-203635112ad2)

**Comment by bys0318** [comment]
It is calculated by the number of tokens with ChatGLM3 tokenizer.
