### ISSUE TITLE
关于packing loss的问题

### ISSUE THREAD

**Issue by mxjmtxrm** [THUDM/LongAlign#8]
1.请问eq4是eq3 scale K/NiM得到的吗？有点疑惑如何得到eq4的？
2.代码中的weight是1/Ni吗？
比如input=[1,1,1,1,2,2,3,3,],label=[-100,-100,-100,1,-100,2,-100,3,] ，weight=[0,0,0,1/4,0,1/2,0,1/2]对吗？然后loss再乘weight是嘛
3.文中讲说scale the loss in the i-th sequence by K/(NiM )，代码中是如何实现的呢？

**Comment by bys0318** [comment]
Sorry，看漏了你的issue。希望以下能回答你的几个问题：
1. Eq 4的L'对Eq 3的L'计算有两点改变，一是对序列i的loss乘以K/(NiM)，二是将之前对所有序列的loss求平均改成对所有序列的loss求和。
2. 没错，代码中的weight是1/Ni，是在预处理的[sort_and_group.py](https://github.com/THUDM/LongAlign/blob/main/sort_and_group.py)中计算并存储的。请注意，Ni是序列i中target token的数量——每个序列的所有target token上的权重之和都为1。在你的例子中，三个序列的target token数量均为1，所以weight=[0,0,0,1,0,1,0,1]。
3. Ni在预处理时和已经每个pack搭配后存好了。在训练时，K是GPU的数量，比如8，是一个常数。M在dataset中预先计算好，随着每个batch一起传入模型中。

**Comment by mxjmtxrm** [comment]
请问如果每次训练的GPU数量不同的话，是需要每次都做一次sort and group吗？

**Comment by bys0318** [comment]
是的
