### ISSUE TITLE
Prediction Results of LongBench-Chat

### ISSUE THREAD

**Issue by guanzhchen** [THUDM/LongAlign#9]
Hi,
Thanks for your awesome work! Could you please provide the prediction results or scores of GPT-4, Claude, LongAlign-7B for all test cases in the LongBench-Chat? I found there may be some Chinese test cases while some models (e.g., Mistral) can't handle well. I hope it would be better to have an EN-only evaluation to make fair comparison in my evaluation.

**Comment by bys0318** [comment]
Thanks for your interest in our work. The [predictions.zip](https://github.com/user-attachments/files/15566954/predictions.zip) you asked for are attached.

**Comment by guanzhchen** [comment]
Many thanks!
